version: '3'

services:
    nginx:
        platform: linux/amd64 
        # image: nginx:latest
        image: wp-nginx:customix
        depends_on:
          - php-fpm
        ports:
         - "80:80"
        #  - "443:443"
        volumes:
          - ./wordpress_uat:/var/www/html
        #  - ./nginx/conf.d:/etc/nginx/conf.d
        #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #  - ./wordpress_uat:/var/www/html
        #  - ./snippets:/etc/nginx/snippets
        #  - ./logs/:/var/log/nginx
        networks:
          nginxnetwork: {}
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: pma
    #   links:
    #     - db
    #   environment:
    #     PMA_HOST: db
    #     PMA_PORT: 3306
    #     PMA_ARBITRARY: 1
    #   restart: always
    #   ports:
    #     - "8081:80"  
    #   networks:
    #     nginxnetwork: {}
    php-fpm:
      # platform: linux/amd64 
      # image: wordpress:php8.0-fpm-alpine
      image: wp-fpm:customix
      # build:
      #   context: .
      #   dockerfile: dockerfile
      # depends_on:
      #  - db
      environment:
        WORDPRESS_DB_HOST: 172.31.17.215:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: isylzjko
        WORDPRESS_DB_NAME: wordpress_nginx
        # WORDPRESS_DEBUG: "true"
        WORDPRESS_REDIS_HOST: redis:6379
      volumes:
        - ./wordpress_uat:/var/www/html
        - ./fpm-config:/usr/local/etc/php-fpm.d
      #   - ./wordpress_uat:/var/www/html
      #   - ./php/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      networks:
        nginxnetwork: {}
    # db:
    #   platform: linux/amd64 
    #   image: mysql:5.7
    #   ports:
    #    - "3306:3306"
    #   environment:
    #     MYSQL_ROOT_PASSWORD: password
    #     MYSQL_DATABASE: wordpress
    #     MYSQL_USER: wordpress
    #     MYSQL_PASSWORD: isylzjko
    #   volumes:
    #     - ./db_data:/var/lib/mysql
    #   networks:
    #     nginxnetwork: {}
volumes:
  wordpress:
    external: true
networks:
  nginxnetwork:
    external : true
    name : nginxnetwork
