FROM nginx:latest


WORKDIR /var/www/html

# COPY ./wordpress_uat/ .

# RUN chmod -R 777 /var/www/html

COPY ./nginx/conf.d /etc/nginx/conf.d
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./logs/ /var/log/nginx

RUN chmod -R 777 /var/log/nginx
COPY ./snippets /etc/nginx/snippets

